import { WeaponAttack, WeaponType, ShieldType } from '../types/GameTypes';

export class WeaponAttackDatabase {
  private static weaponAttacks: Map<WeaponType | ShieldType, WeaponAttack[]> = new Map([
    ['dagger', [
      {
        name: 'Light Attack',
        actionCost: 1,
        staminaCost: 3,
        damageMultiplier: 1,
        hitBonus: 0,
        conditionInflicted: 'bleeding',
        conditionChance: 15,
        conditionDuration: 2,
        specialEffect: 'Standard attack',
        availableWithShield: true,
        requiresDualWield: false,
      },
      {
        name: 'Backstab',
        actionCost: 2,
        staminaCost: 10,
        damageMultiplier: 3,
        hitBonus: 0,
        conditionInflicted: 'bleeding',
        conditionChance: 35,
        conditionDuration: 2,
        specialEffect: 'Crit on 19-20, once per target or if target is stunned',
        availableWithShield: true,
        requiresDualWield: false,
      },
    ]],
    
    ['shortsword', [
      {
        name: 'Light Attack',
        actionCost: 1,
        staminaCost: 5,
        damageMultiplier: 1,
        hitBonus: 0,
        conditionInflicted: 'dependable',
        conditionChance: 100,
        conditionDuration: 1,
        specialEffect: 'Standard attack, dependable',
        availableWithShield: true,
        requiresDualWield: false,
      },
      {
        name: 'Disarming Strike',
        actionCost: 2,
        staminaCost: 10,
        damageMultiplier: 1,
        hitBonus: 0,
        conditionInflicted: 'raise_evasion',
        conditionChance: 100,
        conditionDuration: 1,
        specialEffect: 'Raises evasion by 3 and damage reduction by 10% for 1 round, dependable',
        availableWithShield: true,
        requiresDualWield: false,
      },
    ]],
    
    ['rapier', [
      {
        name: 'Light Attack',
        actionCost: 1,
        staminaCost: 5,
        damageMultiplier: 1,
        hitBonus: 0,
        conditionInflicted: 'bleeding',
        conditionChance: 25,
        conditionDuration: 2,
        specialEffect: '10% chance to attack again on successful strike',
        availableWithShield: true,
        requiresDualWield: false,
      },
      {
        name: 'Puncture',
        actionCost: 2,
        staminaCost: 15,
        damageMultiplier: 1,
        hitBonus: 0,
        conditionInflicted: 'bleeding',
        conditionChance: 40,
        conditionDuration: 2,
        specialEffect: 'Lunge and attack the target three times',
        availableWithShield: true,
        requiresDualWield: false,
      },
    ]],
    
    ['longsword', [
      {
        name: 'Light Attack',
        actionCost: 1,
        staminaCost: 5,
        damageMultiplier: 1,
        hitBonus: 0,
        specialEffect: 'Standard attack',
        availableWithShield: true,
        requiresDualWield: false,
      },
      {
        name: 'Sweeping Strike',
        actionCost: 2,
        staminaCost: 10,
        damageMultiplier: 1,
        hitBonus: 0,
        specialEffect: 'Cleaving momentum deal 75% damage to surrounding enemies',
        availableWithShield: true,
        requiresDualWield: false,
      },
    ]],
    
    ['battleaxe', [
      {
        name: 'Rend',
        actionCost: 1,
        staminaCost: 5,
        damageMultiplier: 1,
        hitBonus: 0,
        conditionInflicted: 'bleeding',
        conditionChance: 10,
        conditionDuration: 2,
        specialEffect: 'A rending attack that has a chance to cause bleed',
        availableWithShield: true,
        requiresDualWield: false,
      },
      {
        name: 'Sweeping Rend',
        actionCost: 2,
        staminaCost: 10,
        damageMultiplier: 1.5,
        hitBonus: 0,
        conditionInflicted: 'bleeding',
        conditionChance: 30,
        conditionDuration: 2,
        specialEffect: 'A sweeping strike that has a chance to cause bleed',
        availableWithShield: true,
        requiresDualWield: false,
      },
    ]],
    
    ['mace', [
      {
        name: 'Light Attack',
        actionCost: 1,
        staminaCost: 5,
        damageMultiplier: 1,
        hitBonus: 0,
        conditionInflicted: 'stunned',
        conditionChance: 10,
        conditionDuration: 2,
        specialEffect: 'Standard attack, stun chance is doubled on a critical strike',
        availableWithShield: true,
        requiresDualWield: false,
      },
      {
        name: 'Crushing Blow',
        actionCost: 2,
        staminaCost: 10,
        damageMultiplier: 1.5,
        hitBonus: 0,
        conditionInflicted: 'stunned',
        conditionChance: 30,
        conditionDuration: 2,
        specialEffect: 'Hard hitting attack, stun chance is tripled on a critical strike',
        availableWithShield: true,
        requiresDualWield: false,
      },
    ]],
    
    ['warhammer', [
      {
        name: 'Light Attack',
        actionCost: 1,
        staminaCost: 5,
        damageMultiplier: 1,
        hitBonus: 0,
        conditionInflicted: 'stunned',
        conditionChance: 15,
        conditionDuration: 1,
        specialEffect: 'Standard attack, stun chance is doubled on a critical strike',
        availableWithShield: true,
        requiresDualWield: false,
      },
      {
        name: 'Heavy Attack',
        actionCost: 2,
        staminaCost: 10,
        damageMultiplier: 1.5,
        hitBonus: 0,
        conditionInflicted: 'stunned',
        conditionChance: 33,
        conditionDuration: 1,
        specialEffect: 'Hard hitting attack, stun chance is tripled on a critical strike',
        availableWithShield: true,
        requiresDualWield: false,
      },
    ]],
    
    ['spear', [
      {
        name: 'Light Attack',
        actionCost: 1,
        staminaCost: 5,
        damageMultiplier: 1,
        hitBonus: 0,
        conditionInflicted: 'poisoned',
        conditionChance: 20,
        conditionDuration: 2,
        specialEffect: 'Standard attack with chance on hit to poison target',
        availableWithShield: true,
        requiresDualWield: false,
      },
      {
        name: 'Vipers Fangs',
        actionCost: 2,
        staminaCost: 10,
        damageMultiplier: 1.5,
        hitBonus: 0,
        conditionInflicted: 'poisoned',
        conditionChance: 25,
        conditionDuration: 2,
        specialEffect: 'On a successful hit performs a second attack',
        availableWithShield: true,
        requiresDualWield: false,
      },
    ]],
    
    ['greatsword', [
      {
        name: 'Thrust',
        actionCost: 1,
        staminaCost: 5,
        damageMultiplier: 1,
        hitBonus: 0,
        specialEffect: 'Standard attack',
        availableWithShield: false,
        requiresDualWield: false,
      },
      {
        name: 'Heavy Attack',
        actionCost: 2,
        staminaCost: 10,
        damageMultiplier: 1,
        hitBonus: 0,
        conditionInflicted: 'bleeding',
        conditionChance: 15,
        conditionDuration: 2,
        specialEffect: 'Hard-hitting; slower recovery',
        availableWithShield: false,
        requiresDualWield: false,
      },
      {
        name: 'Arcing Blade',
        actionCost: 1,
        staminaCost: 10,
        damageMultiplier: 1,
        hitBonus: 0,
        conditionInflicted: 'bleeding',
        conditionChance: 25,
        conditionDuration: 1,
        specialEffect: 'Wide arcing attack that strikes all enemies in combat, with a chance to inflict bleed',
        availableWithShield: false,
        requiresDualWield: false,
      },
      {
        name: 'Crimson Mist',
        actionCost: 2,
        staminaCost: 20,
        damageMultiplier: 2,
        hitBonus: 0,
        conditionInflicted: 'decapitate',
        conditionChance: 35,
        conditionDuration: 1,
        specialEffect: 'Powerful overhead strike, crit on 18-20, 35% chance to instantly kill enemies under 30% health on critical strike',
        availableWithShield: false,
        requiresDualWield: false,
      },
    ]],
    
    ['greataxe', [
      {
        name: 'Light Attack',
        actionCost: 1,
        staminaCost: 5,
        damageMultiplier: 1,
        hitBonus: 0,
        conditionInflicted: 'bleeding',
        conditionChance: 20,
        conditionDuration: 2,
        specialEffect: 'Fast attack that can cause a bleed effect',
        availableWithShield: false,
        requiresDualWield: false,
      },
      {
        name: 'Savage Strike',
        actionCost: 2,
        staminaCost: 10,
        damageMultiplier: 1,
        hitBonus: 0,
        specialEffect: 'A hard hitting attack, crit on 19-20 and roll additional xd12 on critical strikes',
        availableWithShield: false,
        requiresDualWield: false,
      },
      {
        name: 'Bloodfury',
        actionCost: 1,
        staminaCost: 10,
        damageMultiplier: 1,
        hitBonus: 0,
        conditionInflicted: 'vampiric',
        conditionChance: 100,
        conditionDuration: 0,
        specialEffect: 'On bleeding targets heal 50% of damage dealt',
        availableWithShield: false,
        requiresDualWield: false,
      },
      {
        name: 'Murderous Intent',
        actionCost: 2,
        staminaCost: 20,
        damageMultiplier: 2,
        hitBonus: 0,
        conditionInflicted: 'bleeding',
        conditionChance: 55,
        conditionDuration: 2,
        specialEffect: 'Savage arcing strike that hits all enemies, if an enemy dies make an additional savage strike at no stamina cost',
        availableWithShield: false,
        requiresDualWield: false,
      },
    ]],
    
    ['quarterstaff', [
      {
        name: 'Light Attack',
        actionCost: 1,
        staminaCost: 5,
        damageMultiplier: 1,
        hitBonus: 0,
        conditionInflicted: 'stunned',
        conditionChance: 10,
        conditionDuration: 1,
        specialEffect: 'Fast concussive strikes',
        availableWithShield: false,
        requiresDualWield: false,
      },
      {
        name: 'Guarding Strike',
        actionCost: 2,
        staminaCost: 10,
        damageMultiplier: 1.5,
        hitBonus: 0,
        conditionInflicted: 'raise_evasion',
        conditionChance: 100,
        conditionDuration: 1,
        specialEffect: 'A quick and powerful strike that also raises evasion by +5 for one round',
        availableWithShield: false,
        requiresDualWield: false,
      },
      {
        name: 'Rising Oak',
        actionCost: 1,
        staminaCost: 10,
        damageMultiplier: 1.2,
        hitBonus: 0,
        conditionInflicted: 'stunned',
        conditionChance: 35,
        conditionDuration: 1,
        specialEffect: 'A powerful strike that can stun a target',
        availableWithShield: false,
        requiresDualWield: false,
      },
      {
        name: 'Spinning Flurry',
        actionCost: 2,
        staminaCost: 20,
        damageMultiplier: 1,
        hitBonus: 0,
        conditionInflicted: 'stunned',
        conditionChance: 30,
        conditionDuration: 1,
        specialEffect: 'Three sweeping strikes, these strikes have a chance to stun all targets',
        availableWithShield: false,
        requiresDualWield: false,
      },
    ]],
    
    ['steel_shield', [
      {
        name: 'Shield Wall',
        actionCost: 1,
        staminaCost: 5,
        damageMultiplier: 0,
        hitBonus: 0,
        conditionInflicted: 'raise_defence',
        conditionChance: 100,
        conditionDuration: 1,
        specialEffect: 'Absorb 10x(y/2) damage (where y = level of shield)',
        availableWithShield: true,
        requiresDualWield: false,
      },
      {
        name: 'Shield Slam',
        actionCost: 2,
        staminaCost: 10,
        damageMultiplier: 1,
        hitBonus: 0,
        conditionInflicted: 'stunned',
        conditionChance: 30,
        conditionDuration: 1,
        specialEffect: 'Absorb 10x(y/2) damage and a chance to stun target',
        availableWithShield: true,
        requiresDualWield: false,
      },
    ]],
    
    ['leather_shield', [
      {
        name: 'Roll',
        actionCost: 1,
        staminaCost: 5,
        damageMultiplier: 1,
        hitBonus: 0,
        conditionInflicted: 'raise_evasion',
        conditionChance: 100,
        conditionDuration: 1,
        specialEffect: 'Roll and raise evasion by 3 for one round',
        availableWithShield: true,
        requiresDualWield: false,
      },
      {
        name: 'Dust Up',
        actionCost: 2,
        staminaCost: 10,
        damageMultiplier: 1,
        hitBonus: 0,
        conditionInflicted: 'raise_evasion',
        conditionChance: 100,
        conditionDuration: 1,
        specialEffect: 'Kick up dust at the enemy, raise evasion by 5 for one round and reduce damage by 15%',
        availableWithShield: true,
        requiresDualWield: false,
      },
    ]],
  ]);

  static getAttacksForWeapon(weaponType: WeaponType | ShieldType): WeaponAttack[] {
    return this.weaponAttacks.get(weaponType) || [];
  }

  static getAllWeaponTypes(): (WeaponType | ShieldType)[] {
    return Array.from(this.weaponAttacks.keys());
  }

  static hasAttacks(weaponType: WeaponType | ShieldType): boolean {
    const attacks = this.weaponAttacks.get(weaponType);
    return attacks !== undefined && attacks.length > 0;
  }
}
